USE pos;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
SELECT * FROM Employees WHERE Gender = 'Male'
WAITFOR DELAY '00:00:10'
SELECT * FROM Employees WHERE Gender = 'Male'
COMMIT TRANSACTION